# Generated by Django 3.2.4 on 2021-07-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210703_1414'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganisationProfile',
            new_name='UserProfile',
        ),
    ]
